/* 🤖 this file was generated by svg-to-ts*/
export const svgs = {
  '0':
    '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 40 40"><path fill="#000" d="M40 40V0H0c0 22.091 17.909 40 40 40z"/></svg>',
  '1':
    '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 40 40"><path fill="#000" d="M0 40V0h40c0 22.091-17.909 40-40 40z"/></svg>',
  '2':
    '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 40 40"><path fill="#000" d="M0 0v40h40C40 17.909 22.091 0 0 0z"/></svg>',
  '3':
    '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 40 40"><path fill="#000" d="M40 0v40H0C0 17.909 17.909 0 40 0z"/></svg>',
  '4':
    '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 40 40"><circle cx="20" cy="20" r="20" fill="#000"/></svg>',
  '5':
    '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 40 40"><circle cx="20" cy="20" r="10" fill="#000"/></svg>',
  '6':
    '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 40 40"><path fill="#000" d="M0 0c0 22.091 17.909 40 40 40C40 17.909 22.091 0 0 0z"/></svg>',
  '7':
    '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 40 40"><path fill="#000" d="M0 40C0 17.909 17.909 0 40 0c0 22.091-17.909 40-40 40z"/></svg>',
  '8':
    '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 40 40"><path fill="#000" d="M40 0H0l40 40V0z"/></svg>',
  '9':
    '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 40 40"><path fill="#000" d="M0 0h40L0 40V0z"/></svg>',
  '10':
    '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 40 40"><path fill="#000" d="M0 40h40L0 0v40z"/></svg>',
  '11':
    '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 40 40"><path fill="#000" d="M40 40H0L40 0v40z"/></svg>',
  '12':
    '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 40 40"><path fill="#000" d="M20 40c0-11.046-8.954-20-20-20v20h20z"/></svg>',
  '13':
    '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 40 40"><path fill="#000" d="M20 40c0-11.046 8.954-20 20-20v20H20z"/></svg>',
  '14':
    '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 40 40"><path fill="#000" d="M20 0c0 11.046 8.954 20 20 20V0H20z"/></svg>',
  '15':
    '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 40 40"><path fill="#000" d="M20 0c0 11.046-8.954 20-20 20V0h20z"/></svg>'
};
